name: 'Test Report'
on:
  workflow_run:
    workflows: [ 'Build' ]
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # libsass.dylib is not working on macos-14
        os: [windows-latest, ubuntu-latest, macos-13]
    steps:
      - name: Process Test Results
        uses: dorny/test-reporter@v1
        with:
          artifact: test-results-${{ matrix.os }}
          name: 'Test Results (${{ matrix.os }})'
          path: '**/*.trx'
          reporter: dotnet-trx